name: "⭐ Feature or enhancement request"
description: Propose something new.
labels:
- enhancement
assignees:
- 4c65736975
body:
- type: textarea
  attributes: 
    label: Description of the new feature / enhancement
    placeholder: What is the expected behavior of the proposed feature?
  validations:
    required: true
- type: textarea
  attributes:
    label: Scenario when this would be used?
    placeholder: What is the scenario this would be used? Why is this important to your game experience?
  validations:
    required: true